import { TYPES } from "./actions";

const initialState = {
  products: [
    {
      id: 1,
      name: 'Notebook Kelyx KL3450 14" Ryzen 5 3450U 8GB RAM 240GB SSD M.2 W10',
      price: 135096,
      category: "Notebooks",
      subCategory: "Notebooks AMD",
      desc: null,
      specs: {
        General: {
          Color: "",
          Type: "",
          OS: "",
          CPUType: "",
          CPUModel: "",
          GPUModel: "",
          ProcessorsFamily: "",
        },
        Storage: {
          StorageCapacity: "",
          SDReader: "",
        },
        Connectivity: {
          HDMI: "",
          USB: "",
          Ethernet: "",
          Bluetooth: "",
          WIFI: "",
          WebCam: "",
          KeyboardLayout: "",
          NumPad: "",
        },
        Dimensions: {
          Weight: "",
          Width: "",
          Depth: "",
          Height: "",
        },
        Display: {
          Size: "",
          Type: "",
          MaxRes: "",
        },
        Memory: {
          RAM: "",
          MemoryGen: "",
          RAMSlot: "",
        },
      },
      img: "https://i.imgur.com/XGAkX0H.jpeg",
      reputation: 3,
    },
    {
      id: 2,
      name: 'Notebook HP 245 14" AMD Athlon 3020E 8GB Ram 240GB SSD',
      price: 159908,
      category: "Notebooks",
      subCategory: "Notebooks AMD",
      desc: null,
      img: "https://i.imgur.com/rB9iSP2.jpg",
      reputation: 2,
    },
    {
      id: 3,
      name: 'Notebook HP 245 G8 14" AMD Ryzen 3 5300U 8GB Ram 1TB HDD W10H',
      price: 186800,
      category: "Notebooks",
      subCategory: "Notebooks AMD",
      desc: null,
      img: "https://i.imgur.com/rB9iSP2.jpg",
      reputation: 3,
    },
    {
      id: 4,
      name: 'Notebook HP 445 14" AMD Ryzen 5 5600U 8GB Ram 256GB SSD W10 PRO',
      price: 288206,
      category: "Notebooks",
      subCategory: "Notebooks AMD",
      desc: null,
      img: "https://i.imgur.com/aivzFQG.jpg",
      reputation: 4,
    },
    {
      id: 5,
      name: 'Notebook Lenovo ThinkPad E15 15.6" AMD Ryzen 5 5500U 8GB 256GB SSD W10H',
      price: 293543,
      category: "Notebooks",
      subCategory: "Notebooks AMD",
      desc: null,
      img: "https://i.imgur.com/wbrrEaU.jpg",
      reputation: 4,
    },
    {
      id: 6,
      name: 'Notebook Hyundai 14.1" Hybook Intel Celeron N4020 4GB Ram 128GB SSD W10',
      price: 72952,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/8YqDAb4.jpg",
      reputation: 2,
    },
    {
      id: 7,
      name: 'Notebook Gfast 14" N-110 Intel Celeron N4020 4GB Ram 128GB SSD Windows 11 Home',
      price: 77388,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/tuw83yQ.jpg",
      reputation: 2,
    },
    {
      id: 8,
      name: 'Notebook Asus X515EA 15.6" Intel I3 1115G4 4GB Ram 256 SSD',
      price: 151499,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/67S7x6W.jpg",
      reputation: 3,
    },
    {
      id: 9,
      name: 'Notebook Asus 14" Pentium N6000 4GB Ram 128GB SSD W11H',
      price: 155671,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/3LO2m4X.jpg",
      reputation: 2,
    },
    {
      id: 10,
      name: 'Notebook Asus X515EA 15.6" Intel I5 1135G7 8GB Ram 256 SSD',
      price: 209146,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/RvTS4BE.jpg",
      reputation: 4,
    },
    {
      id: 11,
      name: 'Notebook Lenovo ThinkPad L15 G2 15.6" Intel I3 1115G4 8GB Ram 256GB SSD W10H',
      price: 240171,
      category: "Notebooks",
      subCategory: "Notebooks INTEL",
      desc: null,
      img: "https://i.imgur.com/oH5XBgM.jpg",
      reputation: 4,
    },
    {
      id: 12,
      name: "PC De Escritorio Armada Completa AMD KIT Ryzen 7 4700S 16GB 240GB SSD GT 210",
      price: 109034,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/UUpfTuS.jpg",
      reputation: 2,
    },
    {
      id: 13,
      name: "PC Armada Completa AMD Ryzen 5 4600G 16GB SSD 480GB + Mouse de regalo",
      price: 157941,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/z60njkV.jpg",
      reputation: 3,
    },
    {
      id: 14,
      name: "PC Gamer Armada Completa AMD Ryzen 5 5600G 16GB 480GB SSD",
      price: 187538,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/7dfL6ZA.jpg",
      reputation: 3,
    },
    {
      id: 15,
      name: "PC Gamer Armada Completa AMD Ryzen 5 5600G 16GB SSD NVME 256GB HDD 1TB",
      price: 212830,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/7dfL6ZA.jpg",
      reputation: 4,
    },
    {
      id: 16,
      name: "PC Armada Completa AMD Ryzen 5 5600G 16GB SSD 1TB + Mouse de Regalo",
      price: 220101,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/7dfL6ZA.jpg",
      reputation: 4,
    },
    {
      id: 17,
      name: "PC Armada Completa AMD Ryzen 5 5600X 16GB SSD NVME 512GB HDD 1TB RTX 3060ti + Mouse de regalo",
      price: 559111,
      category: "Desktop",
      subCategory: "Desktop AMD",
      desc: null,
      img: "https://i.imgur.com/wWaBk9w.jpg",
      reputation: 5,
    },
    {
      id: 18,
      name: "PC de Escritorio Armada Completa Intel Pentium G6405 8GB SSD 240GB",
      price: 85572,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/s3XCZRJ.jpg",
      reputation: 2,
    },
    {
      id: 19,
      name: "PC Oficina Armada Completa Intel Pentium G6400 8GB SSD 240GB",
      price: 95133,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/c1f5rq5.jpg",
      reputation: 3,
    },
    {
      id: 20,
      name: "PC de Escritorio Armada Completa Intel i3 10100 8GB SSD 240GB",
      price: 109660,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/7P7op90.jpg",
      reputation: 3,
    },
    {
      id: 21,
      name: "PC de Escritorio Armada Completa Intel I3 12100 8GB SSD 240GB",
      price: 125239,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/HdunYDX.jpg",
      reputation: 3,
    },
    {
      id: 22,
      name: "PC Gamer Armada Completa Intel I3 10105F 16GB SSD 240 RX 550",
      price: 165120,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/ymzPn6Q.png",
      reputation: 4,
    },
    {
      id: 23,
      name: "PC Gamer Armada Completa Intel I3 10105F 16GB SSD 240 HDD 1TB RX 580",
      price: 227332,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/W0BVnB5.jpg",
      reputation: 4,
    },
    {
      id: 24,
      name: "PC Gamer Armada Completa Intel I5 10400F 16GB SSD 240 HDD 1TB RX 580",
      price: 259093,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/fyaPD9R.jpg",
      reputation: 4,
    },
    {
      id: 25,
      name: "PC Gamer Armada Completa Intel I3 12100F 16GB SSD NVME 512GB HDD 1TB RTX 3060 + Mouse de Regalo",
      price: 403747,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/ekFCtVy.jpg",
      reputation: 5,
    },
    {
      id: 26,
      name: "PC Gamer Armada Completa Intel I5 10600K 16GB SSD NVME 512GB HDD 1TB RTX 3060TI",
      price: 512434,
      category: "Desktop",
      subCategory: "Desktop INTEL",
      desc: null,
      img: "https://i.imgur.com/ZTVe8MP.jpg",
      reputation: 5,
    },
    {
      id: 27,
      name: "Motherboard MSI A320M-A PRO AM4",
      price: 19708,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/NrAqUGf.jpg",
      reputation: 1,
    },
    {
      id: 28,
      name: "MOTHER GIGABYTE A520M S2H AM4",
      price: 23337,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/pnRw00b.png",
      reputation: 2,
    },
    {
      id: 29,
      name: "MOTHER MSI B450M PRO-VDH MAX BOX M-ATX AM4",
      price: 24134,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/Zdl8qeS.png",
      reputation: 2,
    },
    {
      id: 30,
      name: "MOTHER MSI X470 GAMING PLUS MAX AM4",
      price: 35305,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/wvVqfTJ.png",
      reputation: 3,
    },
    {
      id: 31,
      name: "MOTHER GIGABYTE B550M AORUS ELITE AM4",
      price: 48739,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/AaOGcTO.png",
      reputation: 4,
    },
    {
      id: 32,
      name: "MOTHER MSI B550 MPG GAMING PLUS AM4",
      price: 81472,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/9ZlXvLh.jpg",
      reputation: 5,
    },
    {
      id: 33,
      name: "MOTHER ASUS B550-F ROG STRIX GAMING WIFI BOX ATX AM4",
      price: 101418,
      category: "Motherboards",
      subCategory: "AMD AM4",
      desc: null,
      img: "https://i.imgur.com/DIQU4qT.jpg",
      reputation: 5,
    },
    {
      id: 34,
      name: "Mother Asrock  H610M-HDV INTEL LGA1700 12ava Gen",
      price: 27645,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/Tv9OTnX.png",
      reputation: 1,
    },
    {
      id: 35,
      name: "MOTHER INTEL GIGABYTE H610M S2H DDR4 LGA1700",
      price: 35424,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/HmYB8lf.png",
      reputation: 2,
    },
    {
      id: 36,
      name: "MOTHER GIGABYTE B660M DS3H AX DDR4 1.2 LGA1700 12VA",
      price: 57029,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/Ajj6qRB.jpg",
      reputation: 3,
    },
    {
      id: 37,
      name: "MOTHER GIGABYTE Z690 GAMINGX GEN12 INTEL",
      price: 78265,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/NnP6v0l.png",
      reputation: 4,
    },
    {
      id: 38,
      name: "MOTHER GIGABYTE B660M A PRO AX DDR4 LGA1700",
      price: 94306,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/IMjh3xw.png",
      reputation: 5,
    },
    {
      id: 39,
      name: "MOTHER ASUS ROG STRIX Z690-E GAMING WIFI D5 BOX LGA1700",
      price: 130415,
      category: "Motherboards",
      subCategory: "LGA 1700",
      desc: null,
      img: "https://i.imgur.com/154FaCh.jpg",
      reputation: 5,
    },
    {
      id: 40,
      name: "Memoria DDR4 8Gb 2400 Kingston HyperX Fury Black",
      price: 17799,
      category: "RAM",
      subCategory: null,
      desc: null,
      img: "https://i.imgur.com/XWZWq2m.jpg",
      reputation: 3,
    },
    {
      id: 41,
      name: "Memoria Ram DDR4 - 16Gb 2X8 3200 Mhz Pny XLR8 Gaming Epic-x Rgb Plateado",
      price: 31799,
      category: "RAM",
      subCategory: null,
      desc: null,
      img: "https://i.imgur.com/h1sAwub.jpg",
      reputation: 4,
    },
    {
      id: 42,
      name: "Memoria Ram DDR4 - 16Gb 2x8 3200 Mhz Corsair Vengance Rgb Pro Negro",
      price: 40999,
      category: "RAM",
      subCategory: null,
      desc: null,
      img: "https://i.imgur.com/QVGakKx.png",
      reputation: 4,
    },
    {
      id: 43,
      name: "Procesador Amd Ryzen 3 3200G 3.8 Ghz + Vega8 - AM4 Sin Cooler",
      price: 41999,
      category: "CPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/NzDHqIw.jpg",
      reputation: 3,
    },
    {
      id: 44,
      name: "Procesador Amd Ryzen 5 5600G 4.4 Ghz - AM4",
      price: 73299,
      category: "CPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/AWAUgOf.jpg",
      reputation: 4,
    },
    {
      id: 45,
      name: "Procesador Amd Ryzen 7 5800X 4.7 Ghz + Watercooler",
      price: 190998,
      category: "CPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/6Td9lkK.jpg",
      reputation: 5,
    },
    {
      id: 46,
      name: "Procesador Amd Ryzen 9 5900X 4.8 Ghz + Watercooler",
      price: 249589,
      category: "CPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/LmERJXL.jpg",
      reputation: 4,
    },
    {
      id: 47,
      name: "Procesador Intel Core i3 12100 4.3 Ghz Alder Lake 1700",
      price: 49989,
      category: "CPU",
      subCategory: "Intel",
      desc: null,
      img: "https://i.imgur.com/TOkuqgE.jpg",
      reputation: 3,
    },
    {
      id: 48,
      name: "Procesador Intel Core i5 12600K 4.9 Ghz Alder Lake 1700 Sin Cooler",
      price: 115399,
      category: "CPU",
      subCategory: "Intel",
      desc: null,
      img: "https://i.imgur.com/EktKttB.jpg",
      reputation: 4,
    },
    {
      id: 49,
      name: "Procesador Intel Core i7 13700K 5.4 Ghz Raptor Lake 1700 Sin Cooler",
      price: 201989,
      category: "CPU",
      subCategory: "Intel",
      desc: null,
      img: "https://i.imgur.com/eDJAJ6J.jpg",
      reputation: 5,
    },
    {
      id: 50,
      name: "Placa De Video GeForce GT 1030 2Gb Gigabyte Low Profile DDR4",
      price: 49689,
      category: "GPU",
      subCategory: "NVIDIA",
      desc: null,
      img: "https://i.imgur.com/917WitE.jpg",
      reputation: 2,
    },
    {
      id: 51,
      name: "Placa De Video LHR GeForce RTX 3050 8Gb Msi Ventus 2X Oc",
      price: 213999,
      category: "GPU",
      subCategory: "NVIDIA",
      desc: null,
      img: "https://i.imgur.com/DPpNdew.jpg",
      reputation: 4,
    },
    {
      id: 52,
      name: "Placa De Video GeForce RTX 3070 Ti 8Gb Msi Ventus 3X Oc",
      price: 259989,
      category: "GPU",
      subCategory: "NVIDIA",
      desc: null,
      img: "https://i.imgur.com/nsvoUWH.jpg",
      reputation: 5,
    },
    {
      id: 53,
      name: "Placa De Video Radeon RX 6500 XT 4Gb Sapphire Pulse Gaming Oc",
      price: 128999,
      category: "GPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/cZWrdW5.jpg",
      reputation: 3,
    },
    {
      id: 54,
      name: "Placa De Video Radeon RX 6650 XT 8Gb Msi Mech 2X Oc",
      price: 164789,
      category: "GPU",
      subCategory: "AMD",
      desc: null,
      img: "https://i.imgur.com/eQ02nFs.jpg",
      reputation: 4,
    },
  ],
  cart: [],
  total: 0,
  count: 0,
};

const cartReducer = (state, action) => {
  switch (action.type) {
    case TYPES.READ_STATE: {
      //actualiza el estado del carrito
      return {
        ...state,
        products: action.payload[0],
        cart: action.payload[1],
        // total: action.payload[2],
        // count: action.payload[3],
      };
    }
    case TYPES.ADD_TO_CART: {
      //agregar a carrito
      let newItem = state.products.find(
        (product) => product.id === action.payload
      );
      let itemInCart = state.cart.find((item) => item.id === newItem.id);

      return itemInCart
        ? {
            ...state,
            cart: state.cart.map((item) =>
              item.id === newItem.id
                ? { ...item, quantity: item.quantity + 1 }
                : item
            ),
            // total: newTotal,
            total: parseFloat(state.total) + parseFloat(newItem.price),
            count: parseFloat(state.count) + 1,
          }
        : {
            ...state,
            cart: [...state.cart, { ...newItem, quantity: 1 }],
            // total: newTotal,
            total: parseFloat(state.total) + parseFloat(newItem.price),
            count: parseFloat(state.count) + 1,
          };

      // return { ...state, cart: [...state.cart, newItem] };
    }
    case TYPES.REMOVE_ITEM: {
      //eliminar 1 item del carrito
      let itemToDelete = state.cart.find((item) => item.id === action.payload);

      return itemToDelete.quantity > 1
        ? {
            ...state,
            cart: state.cart.map((item) =>
              item.id === action.payload
                ? { ...item, quantity: item.quantity - 1 }
                : item
            ),
            total: parseFloat(state.total) - parseFloat(itemToDelete.price),
            count: parseFloat(state.count) - 1,
          }
        : {
            ...state,
            cart: state.cart.filter((item) => item.id !== action.payload),
            total: parseFloat(state.total) - parseFloat(itemToDelete.price),
            count: parseFloat(state.count) - 1,
          };
    }
    case TYPES.REMOVE_ALL_ITEMS: {
      //eliminar todos los items de 1 MISMO tipo
      let itemToDelete = state.cart.find((item) => item.id === action.payload);
      let itemToDeletePrice = itemToDelete.price * itemToDelete.quantity;

      return {
        ...state,
        cart: state.cart.filter((item) => item.id !== action.payload),
        total: parseFloat(state.total) - itemToDeletePrice,
        count: parseFloat(state.count) - parseFloat(itemToDelete.quantity),
      };
    }
    case TYPES.CLEAR_CART: {
      //eliminar todos los items / limpiar carrito
      return initialState;
    }
    default:
      return state;
  }
};

export { initialState };
export default cartReducer;
